# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_t67QNZ5c5F6CsTW2pHu0bxf8syyAn6
"""

import pandas as pd

df = pd.read_csv("export_6876fc80b23c9_20250715211232.csv", sep=";", encoding="utf-8")
df.head()

catalogo = []

for index, row in df.iterrows():
    producto = {
        "sku": str(row["ID Orden"]),
        "nombre": str(row["Descripción"]).strip(),
        "precio": int(str(row["Monto"]).replace("$", "").replace(".", "").replace("CLP", "").strip()),
        "link_pago": str(row["Link de Pago"]).strip()
    }
    catalogo.append(producto)

# Mostrar los 3 primeros productos para confirmar
for p in catalogo[:3]:
    print(p)

def recomendar_producto(nombre_cliente, necesidad, catalogo):
    print(f"👋 Hola {nombre_cliente}, gracias por contactarte con DataIngeniería!")

    # Convertimos la necesidad a minúscula para hacer búsquedas más flexibles
    necesidad = necesidad.lower()

    # Buscamos coincidencias en el nombre del producto
    sugerencias = [p for p in catalogo if necesidad in p["nombre"].lower()]

    if sugerencias:
        print("🧠 Basado en lo que buscas, esto podría interesarte:")
        for s in sugerencias:
            print(f"🔹 {s['nombre']}\n💸 Precio: ${s['precio']} CLP\n🔗 Link de pago: {s['link_pago']}\n")
        print("¿Quieres que te ayude a completar la compra o recibir más opciones?")
    else:
        print("❌ No encontré coincidencias exactas. ¿Podrías darme más detalles para ayudarte mejor?")

recomendar_producto("Juan", "windows", catalogo)

import streamlit as st

# Título del formulario
st.title("🧠 Asistente IA de Ventas - DataIngeniería")

# Entrada de datos del usuario
nombre = st.text_input("👋 ¿Cuál es tu nombre?")
necesidad = st.text_input("📝 ¿Qué estás buscando? (Ej: Windows, Office, Web, Soporte)")

# Lógica de recomendación
if nombre and necesidad:
    sugerencias = [p for p in catalogo if necesidad.lower() in p["nombre"].lower()]

    if sugerencias:
        st.success(f"Hola {nombre}, encontré estas opciones para ti:")
        for producto in sugerencias:
            st.write(f"🔹 {producto['nombre']} — ${producto['precio']} CLP")
            st.markdown(f"[🛒 Comprar ahora con Flow]({producto['link_pago']})", unsafe_allow_html=True)
    else:
        st.warning("No encontré coincidencias exactas. ¿Podrías dar más detalles?")

